# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
# Load default processing options
#imports:
# - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
# - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
#- { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
#    filebrowserBrowseRoute: elfinder
#    filebrowserBrowseRouteParameters: []            