# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
    filter_sets: 
        card: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                size: [200, 200] # Taille de l'image de sortie
                #mode: outbound # Découpage de l'image

        reduced: # Nom du filtre
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]
                    
        filigrane: # Nom du filtre
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                watermark:
                    # chemin vers le fichier
                    image: ../public/assets/img/watermark.png
                    # Taille relative de l'image
                    size: 0.1
                    # set the position of the watermark
                    position: bottomright